# Objectifs scientifiques 🎯

## Description des objectifs scientifiques des enregistrements audio

L'axe 4 du projet Hélicéo consiste à étudier les conditions d'acquisition d'une ou plusieurs langues dans un contexte multilingue afin de comprendre comment l'enfant réussit cet exploit très tôt dans son développement.

Parmi nos questions de recherche pour le projet Hélicéo, il y a l'effet du contexte culturel dans l'acquisition des langues vernaculaires. En effet, des analyses préliminaires sur un échantillon de 15 enfants issus de différentes régions du Vanuatu ont révélé une plus grande tendance à l'utilisation de langues vernaculaires autochtones plutôt que le bislama dans des contextes de transmission culturelle, tels que les chants et les contes traditionnels. Même si la nature des résultats ne démontre pas un lien de cause à effet concernant l'acquisition d'une langue et son contexte d'utilisation, elle montre tout de même que certaines langues sont utilisées de façon privilégiée dans certains contextes, ce qui donne une idée des conditions d'utilisation de ces langues et, possiblement, de leur acquisition.

D'autres études ont montré des effets similaires, où les langues vernaculaires étaient utilisées plus fréquemment dans la transmission de chants et d'histoires traditionnelles (Duhamel, 2020a, cité dans Ridge, 2026 ; Budd, 2011, cité dans Ridge, 2026 ; Crowley, 2004a, cité dans Ridge, 2026). Ce qui peut paraître évident est en réalité un constat important dans le contexte du projet Hélicéo, dont l'un des buts principaux est de soutenir et maintenir en vie des langues océaniennes : soutenir une langue devra peut-être passer par le soutien de la culture qui y est transmise. Une étude récente menée sur le vatlongos confirme statistiquement cette tendance : le type de récit (genre discursif) est l'un des facteurs les plus déterminants dans l'usage du bislama, les récits traditionnels et les contes présentaient la plus faible probabilité d'emprunts au bislama, contrairement aux récits portant sur des événements contemporains ou professionnels (Ridge, 2026).

C'est cette piste que nous souhaitons creuser en priorité, afin d'apporter des preuves soutenant de futures hypothèses et recommandations pratiques, en collaboration avec les autres axes scientifiques du projet. Pour prendre un exemple plus familier : après tout, nous sommes nombreux à avoir appris à parler anglais à travers des paroles de chansons ou de séries américaines. Peut-être que l'un des moyens possibles de préserver et de protéger la transmission de l'héritage linguistique océanien serait de maintenir les activités culturelles liées à cette transmission, telles que les chants et contes traditionnels mais aussi la transmission des connaissances traditionnelles liées à l'environnement naturel.

Pour répondre à ces questions, l'objectif est d'enregistrer l'environnement linguistique quotidien des enfants à travers la technique du *longform recording*, afin de pouvoir analyser les différents contextes d'utilisation d'une langue, mais aussi d'autres variables en lien avec les métadonnées.

Pour ce faire, en fonction du pack de collaboration choisi, soit vous nous envoyez les enregistrements simplement sans annotation, soit, à chaque enregistrement fait et envoyé à notre laboratoire, nous ferons plusieurs extractions de passages de 30 à 60 secondes pour chaque journée enregistrée, que nous vous renverrons dans des tableaux Excel afin d'être réécoutés en présence des membres de la famille enregistrée, dans le but de retranscrire ce qui a été dit par qui et envers qui et dans quelle langue. La suite de l'annotation sera faite de notre côté afin de réduire au maximum le travail de votre côté.

Quel que soit le pack de collaboration choisi, la procédure d'utilisation des izyrec et la méthode de transmission des données resteront les mêmes.

**Référence :**

Ridge, E. (2026). Contact with a contact language: A corpus study of Bislama borrowings in Vatlongos speech. *Journal of Language Contact*, 19, 1–43. [https://doi.org/10.1163/19552629-bja10111](https://doi.org/10.1163/19552629-bja10111)


## Description des objectifs scientifiques du dispositif vidéo (harnais-caméra)

L'axe 4 du projet Hélicéo consiste à étudier les conditions d'acquisition d'une ou plusieurs langues dans un contexte multilingue afin de comprendre comment l'enfant réussit cet exploit très tôt dans son développement.

Cette partie du projet intégrant un dispositif d'enregistrement vidéo s'inscrit dans la continuité du projet SCALa (Tsuji, Cristia & Dupoux, 2021), qui documente la structure de l'input socio-linguistique reçu par l'enfant à partir d'enregistrements longform audio. Des travaux menés dans ce cadre montrent que le *speech input* adressé à l'enfant est très majoritairement référentiellement transparent, c'est-à-dire ancré dans le « ici et maintenant » de l'interaction, plutôt que dans une information déplacée dans le temps ou l'espace. Par exemple, quand un parent dit « regarde, le chat » alors que le chat est physiquement présent et visible devant l'enfant, l'énoncé est référentiellement transparent : l'enfant peut directement faire le lien entre le mot et la chose. À l'inverse, si le parent dit « hier on a vu un chat », l'enfant n'a accès à aucun support visuel pour ancrer le mot, l'information est déplacée. Ce résultat de forte transparence référentielle a été observé aussi bien en anglais qu'en français (Abdou et al., données SCALa), et repose en grande partie sur la présence physique du référent dans l'environnement immédiat de l'enfant au moment de l'énoncé (Veneziano, 2001 ; Fitch et al., 2024).

Or cette structure a été documentée presque exclusivement dans des contextes occidentaux, industrialisés et urbains. Notre question de recherche est de savoir si cette proportion de langage ancré dans l'environnement visuel immédiat de l'enfant varie selon le contexte culturel, en particulier si les enfants des régions rurales en Polynésie sont exposés à un input linguistique qui fait davantage (ou au contraire moins) référence à des objets réellement présents dans leur environnement, comparativement aux enfants européens ou nord-américains déjà documentés dans la littérature. Fitch, Lieberman, Frank, Brough, Valleau et Arunachalam (2024) ont déjà montré que la transparence référentielle des verbes dans le *speech input* varie entre parents japonais et américains, ce qui suggère que cette dimension n'est pas universelle et dépend des pratiques culturelles de communication avec l'enfant, une piste directement transposable à notre comparaison.

Documenter cette dimension suppose cependant de ne plus se fier au seul jugement de l'annotateur pour déterminer si un objet mentionné est présent ou non dans l'environnement de l'enfant au moment de l'énoncé, une information que l'audio seul ne permet pas de vérifier de façon fiable. Un enregistrement vidéo classique ne convient pas non plus : Bergelson, Amatuni, Dailey, Koorathota et Tor (2019) montrent que la présence d'une caméra tenue par un observateur modifie le comportement langagier des interlocuteurs de l'enfant, produisant une image déformée et non représentative de son expérience linguistique quotidienne. C'est pourquoi nous développons une caméra portée sur le torse de l'enfant au moyen d'un harnais, qui permet de capturer en continu son champ visuel sans présence d'observateur, et ainsi de vérifier objectivement, pour chaque énoncé annoté, si le référent linguistique dont il est question était effectivement visible dans l'environnement de l'enfant.

Au-delà de ce codage présent/absent, ce dispositif ouvre la voie à plusieurs axes d'analyse complémentaires. Parmi ces axes, le premier consiste à mesurer, pour chaque énoncé, le délai entre l'apparition visuelle d'un référent dans le champ de la caméra et sa mention verbale par l'adulte, ce qui permettrait de tester plus finement l'hypothèse de la transparence référentielle, avec plusieurs degrés d'alignement audio-visuel plutôt qu'un simple codage binaire. Le deuxième porte sur la proportion de temps passé en intérieur versus en extérieur, une variable qui influence directement la richesse et le type d'objets visibles dans l'environnement de l'enfant, et qui est susceptible de varier fortement entre les contextes ruraux polynésiens et les contextes urbains occidentaux déjà documentés. Le troisième concerne la densité et la composition sociale du champ visuel, combien de personnes sont visibles autour de l'enfant et à quelle distance, une dimension particulièrement pertinente pour comparer les structures d'interaction multipartites, plus fréquentes en contexte communautaire, aux structures dyadiques plus typiques des contextes occidentaux étudiés jusqu'ici. Enfin, le dispositif permet de distinguer la proportion d'objets simplement visibles de celle des objets que l'enfant manipule activement, une distinction déjà mise en évidence par les travaux utilisant des caméras portées à la tête, qui montrent que le champ visuel de l'enfant est en grande partie occupé par ses propres mains et les objets avec lesquels il interagit (Yoshida & Smith, 2008).

Pour répondre à ces questions, l'objectif est d'utiliser une caméra portée sur le torse au moyen d'un harnais, en complément de l'enregistrement audio capté par la caméra elle-même.

Pour ce faire, quel que soit le pack de collaboration choisi, la transmission des données vidéo reste la même (cf. [doc transmission des données](./doc_transmission_donnees.md)). Si l'option de collaboration implique de l'annotation vidéo, une documentation spécifique vous sera alors envoyée.


**Références :**

- Tsuji, S., Cristia, A., & Dupoux, E. (2021). SCALa: A blueprint for computational models of language acquisition in social context. *Cognition*, 213, 104779. [https://doi.org/10.1016/j.cognition.2021.104779](https://doi.org/10.1016/j.cognition.2021.104779)
- Fitch, A., Lieberman, A. M., Frank, M. C., Brough, J., Valleau, M., & Arunachalam, S. (2025). Referential transparency of verbs in child-directed input by Japanese and American caregivers. *Journal of Child Language*, 52(6), 1367–1382. [https://doi.org/10.1017/S0305000924000382](https://doi.org/10.1017/S0305000924000382)
- Bergelson, E., Amatuni, A., Dailey, S., Koorathota, S., & Tor, S. (2019). Day by day, hour by hour: Naturalistic language input to infants. *Developmental Science*, 22(1), e12715. [https://doi.org/10.1111/desc.12715](https://doi.org/10.1111/desc.12715)
- Yoshida, H., & Smith, L. B. (2008). What's in view for toddlers? Using a head camera to study visual experience. *Infancy*, 13(3), 229–248. [https://doi.org/10.1080/15250000802004437](https://doi.org/10.1080/15250000802004437)
